# Generated by Django 4.0 on 2023-04-02 19:29

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('featured_image', models.ImageField(upload_to='Course Images')),
                ('author', models.CharField(max_length=100)),
                ('number_of_lectures', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Self Health', 'Self Health'), ('Mental Health', 'Mental Health'), ('Psycology', 'Psycology'), ('Dental Health', 'Dental Health'), ('Care Giving', 'Care Giving'), ('Physical Fitness and Exercise', 'Physical Fitness and Exercise')], max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('picture', models.ImageField(upload_to='Images')),
                ('hospital', models.CharField(max_length=300)),
                ('bio', models.TextField(max_length=500)),
                ('area_of_specialization', models.CharField(max_length=300)),
                ('approved', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FirstAid',
            fields=[
                ('title', models.CharField(max_length=400)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', primary_key=True, serialize=False)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('featured_image', models.ImageField(upload_to='First Aid')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('title', models.CharField(max_length=300)),
                ('featured_image', models.ImageField(upload_to='blog images')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField()),
                ('publish', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(null=True)),
                ('phone_number', models.CharField(max_length=300)),
                ('how_did_you_hear_about_us', models.TextField()),
                ('what_will_you_use_sigma_for', models.TextField()),
                ('allergies', models.CharField(max_length=400)),
                ('blood_group', models.CharField(max_length=300)),
                ('genotype', models.CharField(max_length=300)),
                ('medical_conditions', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=400)),
                ('nationality', models.CharField(max_length=300)),
                ('medical_history', models.TextField()),
                ('about_me', models.TextField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('video_link', models.CharField(max_length=900)),
                ('description', models.TextField()),
                ('serial_number', models.IntegerField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('date_booked', models.DateField(auto_now_add=True)),
                ('subject', models.CharField(max_length=150)),
                ('email_address', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('booker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor')),
            ],
        ),
    ]
