# Generated by Django 4.0 on 2023-04-01 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.ForeignKey(max_length=300, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
