# Generated by Django 4.0 on 2023-03-25 18:52

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_rename_user_profile_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('featured_image', models.ImageField(upload_to='Course Images')),
                ('author', models.CharField(max_length=100)),
                ('number_of_lectures', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=300, null=True)),
                ('picture', models.ImageField(upload_to='Images')),
                ('hospital', models.CharField(max_length=300, null=True)),
                ('bio', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='what_will_you_use_paradox_for',
        ),
        migrations.AddField(
            model_name='profile',
            name='allergies',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genotype',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='medical_condition',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='what_will_you_use_sigma_for',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='how_did_you_hear_about_us',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('video_link', models.CharField(max_length=900)),
                ('description', models.TextField(null=True)),
                ('serial_number', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500000000, null=True)),
                ('gpt', models.TextField(max_length=1700000000000000000000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email_address', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('booker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
    ]
