# Generated by Django 4.0 on 2023-04-01 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor'),
        ),
    ]
