# Generated by Django 4.0 on 2023-03-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='area_of_specialization',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
