# Generated by Django 4.0 on 2023-03-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doctor_area_of_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='medical_condition',
            new_name='medical_conditions',
        ),
    ]
