# Generated by Django 4.0 on 2023-04-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_alter_doctor_name_alter_doctor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
