# Generated by Django 4.0 on 2023-03-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_medical_condition_profile_medical_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=300, null=False),
        ),
    ]
