# Generated by Django 4.0 on 2023-03-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='approved',
            field=models.CharField(choices=[('yes', 'yes'), ('yes', 'yes')], max_length=250, null=True),
        ),
    ]
