# Generated by Django 4.0 on 2023-03-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_doctor_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='approved',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(default='None', max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
