# Generated by Django 4.0 on 2023-04-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appointment_booker'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('featured_image', models.ImageField(upload_to='blog images')),
                ('body', models.TextField()),
                ('publish', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=200)),
            ],
        ),
    ]
