# Generated by Django 4.0 on 2023-03-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_doctor_id_alter_doctor_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
