# Generated by Django 4.0 on 2023-04-02 11:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_latestnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
