# Generated by Django 4.0 on 2023-03-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_doctor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Self Health', 'Self Health'), ('Mental Health', 'Mental Health'), ('Psycology', 'Psycology'), ('Dental Health', 'Dental Health'), ('Care Giving', 'Care Giving'), ('Physical Fitness and Exercise', 'Physical Fitness and Exercise')], max_length=300, null=True),
        ),
    ]
