# Generated by Django 4.0 on 2023-04-02 11:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_latestnews_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestnews',
            name='id',
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', primary_key=True, serialize=False, unique=True),
        ),
    ]
