# Generated by Django 4.0 on 2023-03-27 11:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_firstaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstaid',
            name='id',
        ),
        migrations.AddField(
            model_name='firstaid',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', primary_key=True, serialize=False),
        ),
    ]
